all:
  hosts:
    burrito:
      ansible_host: Burrito_VPS
      ansible_user: ubuntu
      k3s_api_endpoint: "https://burrito.deway.fr:6443"
      k3s_private_ip: 10.69.34.104
      kubeconfig_local_path: "~/.kube/burrito-k3s.yaml"
  children:
    k3s_agents:
      hosts:
        burrito-node-105:
        burrito-node-106:
