apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: burrito
  namespace: argocd
spec:
  description: Burrito production workloads (evaluation-system namespace)
  sourceRepos:
    - https://github.com/deway-developpement/Burrito.git
  destinations:
    - namespace: evaluation-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: LimitRange
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: networking.k8s.io
      kind: Ingress
    - group: traefik.io
      kind: Middleware
    - group: serving.knative.dev
      kind: Service
    - group: sources.knative.dev
      kind: RedisStreamSource
