apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../evaluation-system.yaml
  - ../../intelligence-fn-rs.knative.yaml
  - ../../frontend.yaml

images:
  - name: burrito-api-gateway
    newName: registry.burrito.deway.fr/burrito-api-gateway
    newTag: latest
  - name: burrito-users-ms
    newName: registry.burrito.deway.fr/burrito-users-ms
    newTag: latest
  - name: burrito-forms-ms
    newName: registry.burrito.deway.fr/burrito-forms-ms
    newTag: latest
  - name: burrito-evaluations-ms
    newName: registry.burrito.deway.fr/burrito-evaluations-ms
    newTag: latest
  - name: burrito-analytics-ms
    newName: registry.burrito.deway.fr/burrito-analytics-ms
    newTag: latest
  - name: burrito-intelligence-fn-rs
    newName: registry.burrito.deway.fr/burrito-intelligence-fn-rs
    newTag: latest
  - name: burrito-groups-ms
    newName: registry.burrito.deway.fr/burrito-groups-ms
    newTag: latest
  - name: burrito-notifications-ms
    newName: registry.burrito.deway.fr/burrito-notifications-ms
    newTag: latest
  - name: registry.burrito.deway.fr/burrito-frontend
    newName: registry.burrito.deway.fr/burrito-frontend
    newTag: latest
