namespace: monitoring

configMapGenerator:
  - name: grafana-dashboard-burrito-uptime
    files:
      - burrito-uptime.json
    options:
      labels:
        grafana_dashboard: "1"
        dashboard_version: "v1.0"
        app: "burrito"

resources:
  - service-monitor-api-gateway.yaml
