namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-dashboard-burrito-uptime
    files:
      - burrito-uptime.json
    options:
      labels:
        grafana_dashboard: "1"
        dashboard_version: "v1.0"
        app: "burrito"
  - name: grafana-dashboard-eval-logs
    files:
      - grafana-dashboard-eval-logs.json
    options:
      labels:
        grafana_dashboard: "1"
        dashboard_version: "v1.0"
        app: "burrito"
  - name: grafana-dashboard-knative-metrics
    files:
      - knative-metrics.json
    options:
      labels:
        grafana_dashboard: "1"
        dashboard_version: "v1.0"
        app: "burrito"

resources:
  - service-monitor-api-gateway.yaml
  - service-monitor-knative-serving.yaml
  - pod-monitor-knative-queue-proxy.yaml
  - pod-monitor-evaluation-istio-proxy.yaml
  - prometheus-rule-api-gateway.yaml
  - loki.yaml
  - promtail.yaml
  - loki-datasource.yaml
