apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: apps-strict
  namespace: evaluation-system
spec:
  selector:
    matchLabels:
      mesh-role: app
  mtls:
    mode: STRICT
